<?php


namespace App\Exports;


use App\Models\RollCall;
use Illuminate\Support\Facades\DB;
use Maatwebsite\Excel\Concerns\FromQuery;
use Maatwebsite\Excel\Concerns\WithCustomStartCell;
use Maatwebsite\Excel\Concerns\WithEvents;
use Maatwebsite\Excel\Concerns\WithHeadings;
use Maatwebsite\Excel\Concerns\WithStyles;
use Maatwebsite\Excel\Concerns\WithTitle;
use Maatwebsite\Excel\Events\AfterSheet;
use Maatwebsite\Excel\Events\BeforeSheet;
use PhpOffice\PhpSpreadsheet\Style\Alignment;
use PhpOffice\PhpSpreadsheet\Style\Border;
use PhpOffice\PhpSpreadsheet\Style\Color;
use PhpOffice\PhpSpreadsheet\Style\Fill;
use PhpOffice\PhpSpreadsheet\Worksheet\Worksheet;

class NotPresentSheet implements FromQuery, WithTitle, WithCustomStartCell, WithEvents
{
    private $title;
    private $sheet_id;
    private $startRow = 6;
    private $headingRowIndex = 5;
    private $data = array();
    private $itemCount = 0;
    private $headingRow = 'A5:D5';
    public function __construct($title, $sheetId, $data)
    {
        $this->title = $title;
        $this->sheet_id = $sheetId;
        $this->data = $data;
    }

    public function query()
    {
        $present_ids = RollCall::query()->where('sheet_id',$this->sheet_id)
            ->select('id')->get()->toArray();
        $this->itemCount = DB::table('eagle_member_info')
            ->whereNotIn('id',$present_ids)->count() + 1;
        return DB::table('eagle_member_info')
            ->whereNotIn('id',$present_ids)
            ->select('id','name','group','phone_number')
            ->orderBy('id');
    }

    public function title(): string
    {
        return $this->title;
    }

    public function registerEvents(): array
    {
        return [
            BeforeSheet::class => [$this,'setInfo'],
            AfterSheet::class => [$this,'setData']


        ];
    }

    public function startCell(): string
    {
        return "A$this->startRow";
    }

    private function createHeading(BeforeSheet $event){


        $event->sheet->getDelegate()->getStyle($this->headingRow)->getFont()->setSize(14);
        $event->sheet->getDelegate()->getStyle($this->headingRow)->getFont()->setBold(true);
        $event->sheet->getDelegate()->getStyle($this->headingRow)->getFont()->setColor(new Color(Color::COLOR_WHITE));
        $event->sheet->getDelegate()->getStyle($this->headingRow)->getActiveSheet()->getRowDimension($this->headingRowIndex)->setRowHeight(30);
//        $event->sheet->getDelegate()->getStyle($cellRange)->getActiveSheet()->getColumnDimension('A')->setWidth(5);
//        $event->sheet->getDelegate()->getStyle($cellRange)->getActiveSheet()->getColumnDimension('B')->setWidth(22);
//        $event->sheet->getDelegate()->getStyle($cellRange)->getActiveSheet()->getColumnDimension('C')->setWidth(22);
//        $event->sheet->getDelegate()->getStyle($cellRange)->getActiveSheet()->getColumnDimension('D')->setWidth(22);
        $event->sheet->getDelegate()->getStyle($this->headingRow)->getActiveSheet()->getStyle($this->headingRow)->getAlignment()->setHorizontal(Alignment::HORIZONTAL_CENTER);
        $event->sheet->getDelegate()->getStyle($this->headingRow)->getActiveSheet()->getStyle($this->headingRow)->getAlignment()->setVertical(Alignment::VERTICAL_CENTER);
        $event->sheet->getDelegate()->getStyle($this->headingRow)->getFill()->setFillType(Fill::FILL_SOLID)
            ->getStartColor()->setARGB('018c1d');
        $event->sheet->getDelegate()->getCell("A$this->headingRowIndex")->setValue('Id');
        $event->sheet->getDelegate()->getCell("B$this->headingRowIndex")->setValue('Name');
        $event->sheet->getDelegate()->getCell("C$this->headingRowIndex")->setValue('Eagle group');
        $event->sheet->getDelegate()->getCell("D$this->headingRowIndex")->setValue('Phone Number');
        return $event;
    }

    public function setInfo(BeforeSheet $event){
        $event = $this->createHeading($event);

        // Sheet Name
        $event = $this->setInfoValue($event,'B1','C1','Sheet Name:',$this->data['sheet_name']);
        //Generated Date
        $event = $this->setInfoValue($event,'B2','C2','Generated Date:',$this->data['generated_date']);
        //Date
        $event = $this->setInfoValue($event,'D1','E1','Sheet Date:',$this->data['sheet_date']);
        //Generated By
        $event = $this->setInfoValue($event,'D2','E2','Generated By:',$this->data['generated_by']);
        //
        $event = $this->setInfoValue($event,'B3','C3','Members present',$this->data['num_present']);


        $event->sheet->getDelegate()->getStyle('B1:B3')->getFont()->setSize(11);
        $event->sheet->getDelegate()->getStyle('B1:B3')->getFont()->setBold(true);
        $event->sheet->getDelegate()->getStyle('B1:B2')->getActiveSheet()->getRowDimension('1')->setRowHeight(20);
        $event->sheet->getDelegate()->getStyle('B1:B2')->getActiveSheet()->getRowDimension('2')->setRowHeight(20);
        $event->sheet->getDelegate()->getStyle('B1:B2')->getActiveSheet()->getRowDimension('3')->setRowHeight(20);
        $event->sheet->getDelegate()->getStyle('D1:D2')->getFont()->setSize(11);
        $event->sheet->getDelegate()->getStyle('D1:D2')->getFont()->setBold(true);

        $event->sheet->getDelegate()->getColumnDimension('A')->setAutoSize(true);
        $event->sheet->getDelegate()->getColumnDimension('B')->setAutoSize(true);
        $event->sheet->getDelegate()->getColumnDimension('C')->setAutoSize(true);
        $event->sheet->getDelegate()->getColumnDimension('D')->setAutoSize(true);
        $event->sheet->getDelegate()->getColumnDimension('E')->setAutoSize(true);
    }

    public function setData(AfterSheet $event){

        $event->sheet->getDelegate()->getStyle($this->headingRow)->applyFromArray([
            'borders' =>[
                'allBorders' => [
                    'borderStyle' => Border::BORDER_THIN,
                    'color' => [ 'argb' => Color::COLOR_BLACK]
                ]
            ]
        ]);

        $contentColumns = ['A','B','C','D'];
        $endCount = $this->headingRowIndex + $this->itemCount;
        foreach ($contentColumns as $column){
            $range = "$column$this->headingRowIndex:$column$endCount";
            $event->sheet->getDelegate()->getStyle($range)->applyFromArray([
                'borders' =>[
                    'allBorders' => [
                        'borderStyle' => Border::BORDER_THIN,
                        'color' => [ 'argb' => Color::COLOR_BLACK]
                    ]
                ]
            ]);
        }
        for($count = 0; $count <= $this->itemCount; $count++){
            $row = $this->startRow + $count;
            $event->sheet->getDelegate()->getRowDimension($row)->setRowHeight(20);
        }
    }

    private function setInfoValue($event,$labelCell,$valueCell,$labelValue,$contentValue){
        $event->sheet->getDelegate()->getCell($labelCell)->setValue($labelValue);
        $event->sheet->getDelegate()->getCell($valueCell)->setValue($contentValue);
        return $event;
    }

}
